### ISSUE TITLE
翻译的结果和谷歌网页翻译的结果不一致。

### ISSUE THREAD

**Issue by song05** [CrazyMayfly/Free-Markdown-Translator#11]
如翻译“We consider a networked Markov decision process (MDP) given as a tuple xxxx”，
在google网页翻译的结果是 “我们考虑以元组 xxxx 形式给出的网络马尔可夫决策过程 (MDP)。”
在Free-Markdown-Translator翻译的结果是 “我们将Markov的网络决策过程（MDP）视为元组xxxx”

是它们调用的翻译接口不一样吗？

**Comment by CrazyMayfly** [comment]
差不多是这样的，不同接口使用的翻译模型不同，造成的翻译质量也不同。
后面考虑换成Bing的翻译接口。
