### ISSUE TITLE
似乎有些新问题

### ISSUE THREAD

**Issue by GeeekerK** [CrazyMayfly/Free-Markdown-Translator#17]
![image-20240817175318503](https://github.com/user-attachments/assets/6f0e4e71-b538-4612-b162-840b2b4e9e1c)

**Comment by CrazyMayfly** [comment]
感谢你发现的问题，这个问题是因为解析配置的时候类型不一致导致的。我现在就修复。

**Comment by CrazyMayfly** [comment]
![image](https://github.com/user-attachments/assets/c41c343f-96df-416e-9c2e-a73af7e6e5f4)
已经更新了发行版

**Comment by GeeekerK** [comment]
LGTM

**Comment by GeeekerK** [comment]
感谢您的开源

**Comment by CrazyMayfly** [comment]
因为热爱，不必客气
