### ISSUE TITLE
config.ph中指定src_language无效

### ISSUE THREAD

**Issue by stvliu** [CrazyMayfly/Free-Markdown-Translator#2]
src_language=‘en’时执行程序，提示Thread-2 (translate_to) is translating zh to zh
运行环境如下：macos 14.2，python 3.12
config.py配置如下：
src_language = "en"
dest_langs = ['zh']

**Comment by stvliu** [comment]
原因猜测：MarkdownTranslator.py第207行，硬编码写死了
translater = MdTranslater('zh', base_dir, detect_filename)
应该修改为
translater = MdTranslater(src_language, base_dir, detect_filename)

**Comment by CrazyMayfly** [comment]
感谢指出，现已更新相关代码
