### ISSUE TITLE
翻译完成的文件包含多余的或减少的空格

### ISSUE THREAD

**Issue by Touch-Night** [CrazyMayfly/Free-Markdown-Translator#7]
1. 表格内容在翻译完成之后会丢失符号|前的一堆空格。例如`| settings | description |`会被翻译成`| 设置| 描述|`。不过这不会影响显示效果。
2. 被某些符号包裹的内容在翻译后，前后各会添加一个空格。例如``.`translate`.``会被翻译成``. `translate` .``，`"conda install -y -c "nvidia/label/cuda-12.1.1" cuda"`会被翻译成`conda install -y -c  "nvidia/label/cuda-12.1.1"  cuda`

**Comment by CrazyMayfly** [comment]
感谢你提出的建议，现在最新版本中
1. 表格中仍然会剔除多余的空格
2. 这个问题是因为在英文等拉丁语系下需要在单词间用空格分隔，现在已经针对该问题做出了优化
